import { chromium } from 'playwright'
const b = await chromium.launch({ args:['--use-gl=swiftshader','--enable-unsafe-swiftshader'] })
const ctx = await b.newContext({ viewport:{width:390,height:844}, isMobile:true, hasTouch:true, offline:true })
const p = await ctx.newPage()
const errs=[]; p.on('pageerror',e=>errs.push(String(e).slice(0,140)))
await p.route('**/*', r => r.request().url().startsWith('file:') ? r.continue() : r.abort())
await p.goto('file:///tmp/offline-app.html', { waitUntil:'load' })
await p.waitForTimeout(10000)
console.log('boot shell:', await p.evaluate(()=>{const s=document.getElementById('boot-shell');return s?(s.className==='gone'?'hidden (app mounted)':'still showing'):'absent'}))
console.log('root children:', await p.evaluate(()=>document.getElementById('root')?.childElementCount))
console.log('hall text:', (await p.evaluate(()=>document.body.innerText.replace(/\s+/g,' ').slice(0,70))))
console.log('page errors:', errs.length, errs.slice(0,2).join(' | '))
// and a cabinet
await p.goto('file:///tmp/offline-app.html#/atoms?q=low', { waitUntil:'load' })
await p.waitForTimeout(12000)
console.log('cabinet canvas:', await p.evaluate(()=>{const c=document.querySelector('canvas');return c?`${c.width}x${c.height}`:'none'}))
await p.screenshot({ path:'/tmp/arcade/shots/offline-atoms.png' })
await b.close()
